# Generated by Django 3.0.3 on 2020-04-01 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0005_auto_20200329_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='datee_created',
        ),
        migrations.AddField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
